# ============================================================================
# EXEMPLOS - SC_TASK PLAYBOOKS (PARA USO COM AAP)
# ============================================================================

# Exemplo de workflow real:
# Job Template 1:
- name: "Etapa 1: Preparar e Iniciar SC_TASK"
  hosts: localhost
  gather_facts: no
  vars:
    # Captura o sys_id da RITM vindo do EDA
    target_ritm_sys_id: "{{ ansible_eda.payload.sys_id }}"

  tasks:
    - name: "Buscar a SC_TASK vinculada à RITM"
      include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: api_info
        servicenow_dispatch_activity: query
        servicenow_api_table: sc_task
        servicenow_api_query: "request_item={{ target_ritm_sys_id }}"
      register: sc_task_find

    - name: "Validar se encontrou uma tarefa"
      fail:
        msg: "Nenhuma SC_TASK encontrada para a RITM {{ ansible_eda.payload.number }}"
      when: sc_task_find.records | length == 0

    - name: "Atualizar SC_TASK: Em Andamento e Atribuição"
      include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        # Usa o sys_id da primeira tarefa encontrada na busca anterior
        sc_task_sys_id: "{{ sc_task_find.records[0].sys_id }}"
        sc_task_new_state: "work_in_progress"
        sc_task_assignment_group: "NOME_DO_GRUPO_AQUI" # Substituir pelo grupo real
        sc_task_assigned_to: "e-mail-do-operador@empresa.com"
        sc_task_comments: "Automação iniciada: Validando dados do usuário {{ ansible_eda.payload.solicitado_para }}."

# Job Template 2:
- name: "Etapa 2: Concluir SC_TASK"
  hosts: localhost
  gather_facts: no
  vars:
    target_ritm_sys_id: "{{ ansible_eda.payload.sys_id }}"

  tasks:
    - name: "Buscar a SC_TASK novamente para garantir o sys_id"
      include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: api_info
        servicenow_dispatch_activity: query
        servicenow_api_table: sc_task
        servicenow_api_query: "request_item={{ target_ritm_sys_id }}"
      register: sc_task_find

    - name: "Finalizar a Tarefa com Sucesso"
      include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: close_task
        sc_task_sys_id: "{{ sc_task_find.records[0].sys_id }}"
        sc_task_new_state: "closed_complete"
        sc_task_close_code: "solved"
        sc_task_close_notes: "Acesso ao Sirius criado com sucesso para o colaborador {{ ansible_eda.payload.matricula }}."
        sc_task_comments: "Prezado(a) {{ ansible_eda.payload.solicitado_por }}, a solicitação de acesso para {{ ansible_eda.payload.solicitado_para }} foi concluída."

# EXEMPLO 1: Criar SC_TASK
- name: "Criar uma nova Catalog Task"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Executar Role"
      include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: create
        sc_task_short_description: "Instalar novo servidor"
        sc_task_description: "Instalação de servidor web Apache"
        sc_task_state: "open"
        sc_task_priority: 3
        sc_task_assignment_group: "IT Infrastructure"
      register: result

    - debug:
        msg: "Tarefa criada com ID: {{ result.record.sys_id }}"

# EXEMPLO 2: Atualizar SC_TASK
- name: "Atualizar descrição da tarefa"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        sc_task_short_description: "Descrição atualizada"
        sc_task_priority: 2

# EXEMPLO 3: Atribuir a um usuário
- name: "Atribuir tarefa a um usuário"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        sc_task_assigned_to: "john.doe@company.com"
        sc_task_new_state: "work_in_progress"

# EXEMPLO 4: Atribuir a um grupo
- name: "Atribuir tarefa a um grupo"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        sc_task_assignment_group: "Database Administration"

# EXEMPLO 5: Mudar status para em progresso
- name: "Iniciar trabalho da tarefa"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        sc_task_new_state: "work_in_progress"
        sc_task_work_notes: "Começando execução da tarefa via Ansible"

# EXEMPLO 6: Fechar como completa
- name: "Fechar tarefa completa"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: close_task
        sc_task_sys_id: "abc123def456"
        sc_task_new_state: "closed_complete"
        sc_task_close_code: "solved"
        sc_task_close_notes: "Tarefa completada com sucesso"

# EXEMPLO 7: Fechar como incompleta
- name: "Fechar tarefa incompleta"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: close_task
        sc_task_sys_id: "abc123def456"
        sc_task_new_state: "closed_incomplete"
        sc_task_close_code: "unable_to_complete"
        sc_task_close_notes: "Não foi possível completar a tarefa"

# EXEMPLO 8: Adicionar comentário (Public)
- name: "Adicionar comentário à tarefa"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        sc_task_comments: "Tarefa completada com êxito. Servidor pronto para uso."

# EXEMPLO 9: Adicionar nota de trabalho (Internal)
- name: "Adicionar nota interna"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        sc_task_work_notes: "Sistema configurado. Todos os testes passaram."

# EXEMPLO 10: Anexar arquivo
- name: "Anexar arquivo à tarefa"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: attach_file
        sc_task_sys_id: "abc123def456"
        attachment_path: "/tmp/relatorio.pdf"
        attachment_name: "Relatório Final"

# EXEMPLO 11: Relacionar com RITM
- name: "Relacionar tarefa com solicitação"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: update
        sc_task_sys_id: "abc123def456"
        ritm_sys_id: "ritm123xyz789"

# EXEMPLO 12: Encerrar tarefa técnica (Workflow Completo)
- name: "Encerrar tarefa técnica"
  hosts: localhost
  tasks:
    - include_role:
        name: servicenow_role
      vars:
        servicenow_dispatch_type: sc_task
        servicenow_dispatch_activity: close_task
        sc_task_sys_id: "abc123def456"
        sc_task_close_code: "solved"
        sc_task_close_notes: "Implantação concluída via automação"
        sc_task_work_notes: "Encerrado automaticamente pelo Playbook de Provisionamento"
        sc_task_approval: "approved"
